### PR TITLE
Allow laravel 9

### PR DESCRIPTION
**Pull request by ankurk91**
Hi,

* Add support for Laravel 9
* Drop support for Laravel 7
* Test on php 8.1
* Drop support for php 7.4

### CODE REVIEW

**Comment by tzsk** [comment]
Thanks for the contribution

**Comment by ankurk91** [comment]
@tzsk

You forgot to tag a new release. 😅

**Comment by tzsk** [comment]
Will do after merging other PRs

**Comment by ankurk91** [comment]
I would suggest to remove `composer.lock` file from repo and keep it in `.gitignore`.

This will remove the noise and reduce the effort to maintain the package.

**Pull request merged**
